// <auto-generated />
namespace Libreria.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tablas6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tablas6));
        
        string IMigrationMetadata.Id
        {
            get { return "201511270716209_tablas6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
